# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2001-2022, Python Software Foundation
# This file is distributed under the same license as the Python package.
#
# Translators:
# Liang-Bo Wang <me@liang2.tw>, 2016
# Matt Wang <mattwang44@gmail.com>, 2021
#
msgid ""
msgstr ""
"Project-Id-Version: Python 3.10\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2018-06-26 18:54+0800\n"
"PO-Revision-Date: 2022-06-11 15:34+0800\n"
"Last-Translator: Matt Wang <mattwang44@gmail.com>\n"
"Language-Team: Chinese - TAIWAN (https://github.com/python/python-docs-zh-"
"tw)\n"
"Language: zh_TW\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Generator: Poedit 3.1\n"

#: ../../library/urllib.error.rst:2
msgid ":mod:`urllib.error` --- Exception classes raised by urllib.request"
msgstr ":mod:`urllib.error` --- urllib.request 引發的例外類別"

#: ../../library/urllib.error.rst:10
msgid "**Source code:** :source:`Lib/urllib/error.py`"
msgstr "**原始碼：**\\ :source:`Lib/urllib/error.py`"

#: ../../library/urllib.error.rst:14
msgid ""
"The :mod:`urllib.error` module defines the exception classes for exceptions "
"raised by :mod:`urllib.request`.  The base exception class is :exc:"
"`URLError`."
msgstr ""
":mod:`urllib.error` module（模組）為 :mod:`urllib.request` 所引發的例外定義了"
"例外 (exception) 類別。基礎例外類別是 :exc:`URLError`。"

#: ../../library/urllib.error.rst:17
msgid ""
"The following exceptions are raised by :mod:`urllib.error` as appropriate:"
msgstr "下列例外會被 :mod:`urllib.error` 適時引發："

#: ../../library/urllib.error.rst:21
msgid ""
"The handlers raise this exception (or derived exceptions) when they run into "
"a problem.  It is a subclass of :exc:`OSError`."
msgstr ""
"處理程式 (handler) 在遇到問題時會引發此例外（或其衍生例外）。它是 :exc:"
"`OSError` 的一個子類別。"

#: ../../library/urllib.error.rst:26
msgid ""
"The reason for this error.  It can be a message string or another exception "
"instance."
msgstr "此錯誤的原因。它可以是一個訊息字串或另一個例外實例。"

#: ../../library/urllib.error.rst:29
msgid ""
":exc:`URLError` has been made a subclass of :exc:`OSError` instead of :exc:"
"`IOError`."
msgstr ""
":exc:`URLError` 已被設為 :exc:`OSError` 而不是 :exc:`IOError` 的子類別。"

#: ../../library/urllib.error.rst:36
msgid ""
"Though being an exception (a subclass of :exc:`URLError`), an :exc:"
"`HTTPError` can also function as a non-exceptional file-like return value "
"(the same thing that :func:`~urllib.request.urlopen` returns).  This is "
"useful when handling exotic HTTP errors, such as requests for authentication."
msgstr ""
"雖然是一個例外（:exc:`URLError` 的一個子類別），:exc:`HTTPError` 也可以作為一"
"個非例外的類檔案回傳值（與 :func:`~urllib.request.urlopen` 所回傳的物件相"
"同）。這適用於處理特殊 HTTP 錯誤，例如為請求認證。"

#: ../../library/urllib.error.rst:44
msgid ""
"An HTTP status code as defined in :rfc:`2616`.  This numeric value "
"corresponds to a value found in the dictionary of codes as found in :attr:"
"`http.server.BaseHTTPRequestHandler.responses`."
msgstr ""
"一個 HTTP 狀態碼，具體定義見 :rfc:`2616`。這個數值會對應到存放在 :attr:`http."
"server.BaseHTTPRequestHandler.responses` 程式碼 dictionary 中的某個值。"

#: ../../library/urllib.error.rst:50
msgid "This is usually a string explaining the reason for this error."
msgstr "這通常是一個解釋本次錯誤原因的字串。"

#: ../../library/urllib.error.rst:54
msgid ""
"The HTTP response headers for the HTTP request that caused the :exc:"
"`HTTPError`."
msgstr "導致 :exc:`HTTPError` 的特定 HTTP 請求的 HTTP 回應 header。"

#: ../../library/urllib.error.rst:61
msgid ""
"This exception is raised when the :func:`~urllib.request.urlretrieve` "
"function detects that the amount of the downloaded data is less than the "
"expected amount (given by the *Content-Length* header).  The :attr:`content` "
"attribute stores the downloaded (and supposedly truncated) data."
msgstr ""
"此例外會在 :func:`~urllib.request.urlretrieve` 函式檢查到已下載的資料量小於期"
"待的資料量（由 *Content-Length* header 給定）時被引發。:attr:`content` 屬性中"
"將存放已下載（可能已被截斷）的資料。"
